services:
  - type: web
    name: lnd-academy-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_TOKEN
        sync: false  # you will set this manually in Render dashboard
